name: Trigger Remote Workflow

on: [push, workflow_dispatch]

jobs:
  trigger-remote:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow via GitHub API
        run: |
          curl -X POST https://api.github.com/repos/leonardosete/teste-ricardinho-destino/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -d '{"event_type": "trigger-workflow"}'
