name: Trigger Remote Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-remote:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger External Workflow
        uses: passeidireto/trigger-external-workflow-action@v1.0.0
        with:
          repository: leonardosete/teste-ricardinho-destino
          event: trigger-workflow
          github_pat: ${{ secrets.GH_PAT }}
